package musicComposition;

//музыкальные стили(жанры) классов
public enum Genre {
	MUSICAL, lIGHTMUSIC, DISKO,
	JAZZRAP, POPRAP, HARDROCKRAP,
	ARTROCK, SYMPHONICROCK, JAZZROCK,
	SICILIANCULTURE, CHILDRENFOLKLORE, BELARUSIANFOLKCULTURE,
	FRENCHSUITE, CHURCHAMERICANCULTURE, GERMANFOLKCULTURE,
	POLISHFOLKCULTURE, TCHAIKOVSKYSYMPHONY, LONDONSYMPHONY,
	CHICAGOSYMPHONY, BOSTONSYMPHONY, BUDAPESHTFESTIVAL,
	MARIINSKYTHEATRE, NEWYORKSYMPHONY, CHOIR, SOLO

}
